apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol | default "TCP" }} # if there is no defined protocol in values.yaml then set default protocol 
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}